version: 2
jobs:
  build:
    working_directory: ~/android-jsc
    docker:
      - image: gengjiawen/android-jsc
    steps:
      - build
      - run:
          name: build aar
          command: |
            ./fetch_sources.sh
            buck build :android-jsc
