version: 2
jobs:
  build:
    working_directory: ~/android-jsc
    docker:
      - image: gengjiawen/android-jsc:feature_abi_support
    environment:
      - ANDROID_NDK: '/opt/android-ndk'
    steps:
      - checkout
      - run:
          name: build aar
          command: |
            ./fetch_sources.sh
            buck build :android-jsc
